[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx\._client
